// Big projects/react-crash-course-v2/src/components/AddTask.js
import { useState } from 'react';

const AddTask = ({ onAdd }) => {
    const [text, setText] = useState('');
    const [day, setDay] = useState('');
    const [reminder, setReminder] = useState(false);

    const onSubmit = (e) => {
        e.preventDefault()

        if (!text) {
            alert('Please add a task');
            return
        }

        onAdd({ text, day, reminder });

        setText('');
        setDay('');
        setReminder(false);
    }

    return (
        <form className="add-form" onSubmit={onSubmit}>
            <div className="form-control">
                <label>Task</label>
                <input type='text' placeholder="Add Task"
                    value={text} onChange={(e) => setText(e.target.value)}></input>
            </div>

            <div className="form-control">
                <label>Day & Time</label>
                <input type='text' placeholder="Add Day & Time"
                    value={day} onChange={(e) => setDay(e.target.value)}     ></input>
            </div>

            <div className="form-control form-control-check">
                <label>Set Reminder</label>
                <input type='checkbox' value={reminder} checked={reminder}
                    onChange={(e) => setReminder(e.currentTarget.checked)} ></input>
            </div>

            <input type="submit" value="Save Task" className="btn btn-block" />
        </form>
    )
}

export default AddTask

// Big projects/angular-crash-v2/src/app/components/add-task/add-task.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Task } from '../../Task';
import { UiService } from '../../services/ui.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-add-task',
  templateUrl: './add-task.component.html',
  styleUrls: ['./add-task.component.css']
})
export class AddTaskComponent implements OnInit {
  @Output() onAddTask: EventEmitter<Task> = new EventEmitter();
  text: string = "";
  day: string = "";
  reminder: boolean = false;
  showAddTask: boolean = false;
  subscription: Subscription;


  constructor(private uiService: UiService) {
    this.subscription = this.uiService.onToggle().subscribe((value) => (this.showAddTask = value));
  }

  ngOnInit(): void {
  }

  onSubmit() {
    if (!this.text) {
      alert("Please add a task.");
      return;
    }

    const newTask = {
      text: this.text,
      day: this.day,
      reminder: this.reminder
    }

    this.onAddTask.emit(newTask);

    this.text = "";
    this.day = "";
    this.reminder = false;

  }

}

<form *ngIf="showAddTask" class="add-form" (ngSubmit)="onSubmit()">
    <div class="form-control">
        <label for="text">Task</label>
        <input type="text" name="text" [(ngModel)]="text" id="text" placeholder="Add text." />
    </div>

    <div class="form-control">
        <label for="day">Day & Time</label>
        <input type="text" name="day" [(ngModel)]="day" id="day" placeholder="Add Day & Time." />
    </div>

    <div class="form-control form-control-check">
        <label for="reminder">Set Reminder</label>
        <input type="checkbox" name="reminder" [(ngModel)]="reminder" id="reminder" />
    </div>

    <input type="submit" value="Save Task" class="btn btn-block" />

</form>
