// Big projects/angular-crash-v1/src/app/components/add-todo/add-todo.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.css']
})
export class AddTodoComponent implements OnInit {

  @Output() addTodo: EventEmitter<any> = new EventEmitter();

  title: string = "";

  constructor() { }

  ngOnInit() { }

  onSubmit() {
    const todo = {
      title: this.title,
      completed: false
    }

    this.addTodo.emit(todo);

  }

}

<form class="form" (ngSubmit)="onSubmit()">
    <input type="text" name="title" [(ngModel)]="title" placeholder="Add Todo Item">
    <input type="submit" value="Submmit" class="btn">
</form>

// Big projects/react-crash-course-v1/src/components/AddTodo.js
import React, { Component } from 'react'

export class AddTodo extends Component {

  state = {
    title: ''
  }

  onChange = (e) => {
    this.setState({[e.target.name]: e.target.value})
  }

  onSubmit = (e) => {
    e.preventDefault();
    this.props.addTodo(this.state.title);
    this.setState({title: ''});
  }

  render() {
    return (
      <form style={{display: 'flex'}} onSubmit={this.onSubmit}>
        <input type="text" name='title' placeholder='Add ToDo'
        style={{flex: '10', padding: '5px'}}
        value={this.state.title} onChange={this.onChange}/>
        <input type="submit" value="submit" className='btn' 
        style={{flex: '1'}}/>

      </form>
    )
  }
}

export default AddTodo
